from pdfExtractor import db

class TaskModel(db.Model):

    """
    TaskModel Class.

    Represents a task in the application.

    Attributes:
    - id (int): Primary key for the task.
    - task_id (str): Celery task ID.
    - file_name (str): Name of the file associated with the task.
    - upload_directory (str): Directory where the file was uploaded.
    - number_of_files_generated (int, optional): Number of csv files generated by the task.
    - status (str): Current status of the task.
    - info (str, optional): Additional information about the task.
    """

    #TODO: status to be set as Enum
    
    __tablename__ = 'tasks'

    id = db.Column(db.Integer, primary_key=True)
    task_id = db.Column(db.String(60), nullable=False, unique=True)
    file_name = db.Column(db.Text, nullable=False)
    upload_directory = db.Column(db.Text, nullable=False)
    number_of_files_generated = db.Column(db.Integer, nullable=True)
    status = db.Column(db.String(25), nullable=False)
    info = db.Column(db.Text, nullable=True)
