"""Add Info column and alter to text field.

Revision ID: 00aa8edcfabe
Revises: 2d87de4210fd
Create Date: 2024-02-11 20:50:41.266458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aa8edcfabe'
down_revision = '2d87de4210fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tasks')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('upload_directory',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('upload_directory',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('info')

    op.create_table('_alembic_tmp_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('upload_directory', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=25), nullable=False),
    sa.Column('number_of_files_generated', sa.INTEGER(), nullable=True),
    sa.Column('info', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###
