"""Add file count column

Revision ID: 2d87de4210fd
Revises: e2b062ea7bba
Create Date: 2024-02-11 19:25:18.554166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87de4210fd'
down_revision = 'e2b062ea7bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_files_generated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('number_of_files_generated')

    # ### end Alembic commands ###
