"""Initial Migrations

Revision ID: 3a04df6a6110
Revises:
Create Date: 2024-02-11 21:10:59.578389

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a04df6a6110"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=60), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("upload_directory", sa.Text(), nullable=False),
        sa.Column("number_of_files_generated", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("info", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
